[package]
name = "HappyDayReminder"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.11.10"
lettre_email = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
handlebars = "4.2"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.38"