smtp:
  host: "smtp.qq.com" # smtp 服务器地址
  port: 465 # 25, 465, 587
  username: "xxxx@qq.com" # 发送邮件的邮箱
  password: "xxxxx" # 发送邮件的邮箱密码/smtp授权码
  to_email: "" # 接收邮件的邮箱
  subject: "生日提醒" # 邮件标题

recipients:
  - name: "用户1"
    birthday: "2023-12-21" # 仅允许输入公历日期
    calendar_type: "lunar" # lunar/solar 默认solar（公历）
  - name: "用户2"
    birthday: "2024-12-09"
    # reminder_days: 3 # 提前几天提醒 TODO:尚未实装

