smtp:
  host: "smtp.qq.com"
  port: 465
  username: "2025502568@qq.com"
  password: "kjjckuicmrfzeicc"
  from_email: "2025502568@qq.com"

recipients:
  - name: "2025502568@qq.com"
    email: "2025502568@qq.com"
  - name: "2025502568@qq.com"
    email: "2025502568@qq.com"

template_path: "email_template.hbs"
