name: Run Released Version
description: "Download and run released version"
inputs:
  version:
    description: 'Version to download (默认最新)'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - name: Download release
      shell: bash
      run: |
        if [ "${{ inputs.version }}" == "latest" ]; then
          # 下载最新版本
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
        else
          # 下载指定版本
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ inputs.version }} | jq -r '.assets[0].browser_download_url')
        fi
        
        curl -L -o program $DOWNLOAD_URL
        chmod +x program

    - name: Run program
      shell: bash
      run: ./program
