name: 'Birthday Actions Bot'

on:
  push:
  schedule:
    # 分，时，天，月，年
    - cron: '0 0 * * *'

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - run:  cargo run
