name: Create Release

on:
  push: # 触发条件：当推送v开头的标签时触发
    tags:
      - 'v*'
  workflow_dispatch: # 手动触发工作流
    inputs:
      tag_version:
        description: "Tag Version"  # 输入描述：标签版本
        required: true  # 必填项
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 配置 Rust
      uses: moonrepo/setup-rust@v1

    - name: 构建项目
      run: cargo build --release

    # - name: 上传构建产物
    #   id: create_release
    #   uses: actions/upload-artifact@v4
    #   with:
    #     path: ./target/release/HappyDayReminder
    #     if-no-files-found: error # 如果没有找到文件则报错
    #     overwrite: true # 覆盖已有文件
    #     compression-level: 0 # 不压缩
    
    - name: Generate artifact attestation
      if: github.ref_type == 'tag' || github.event.inputs.tag_version != ''
      continue-on-error: true
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: |
          ./target/release/HappyDayReminder

    - name: 发布版本
      id: version
      uses: ./.github/actions/setup-version

    - name: 创建 GitHub Release
      if: github.ref_type == 'tag' || github.event.inputs.tag_version != ''
      uses: softprops/action-gh-release@v2
      with:
        name: v${{ steps.version.outputs.APP_VERSION }}
        draft: false
        prerelease: true
        tag_name: v${{ steps.version.outputs.APP_VERSION }}
        files: |
          ./target/release/HappyDayReminder
